import AdminShell from "../../../components/AdminShell";
import { getRecommendationRulesPreview } from "../../../lib/recommendation";
import { getRecommendationSettings } from "../../../lib/recommendation-settings";

function formatPrice(value: number | null | undefined) {
  if (typeof value !== "number") return "—";
  return `$${value.toFixed(2)}`;
}

function formatNumber(value: number | null | undefined) {
  if (typeof value !== "number") return "—";
  return Number.isInteger(value) ? value.toFixed(0) : value.toFixed(1);
}

function parseDataGb(data: string | undefined) {
  if (!data) return null;

  const value = data.trim().toLowerCase();

  if (
    value.includes("unlimited") ||
    value.includes("unbegrenzt") ||
    value.includes("∞")
  ) {
    return null;
  }

  const match = value.match(/(\d+(?:[.,]\d+)?)/);
  if (!match) return 0;

  const amount = Number(match[1].replace(",", "."));

  if (value.includes("mb")) {
    return amount / 1000;
  }

  return amount;
}

function getPlanText(product: {
  data: string;
  validityDays: number;
} | null | undefined) {
  if (!product) return "—";
  return `${product.data} / ${product.validityDays} Days`;
}

function getPriceDifference(
  baseProduct:
    | {
        sellPrice: number;
      }
    | null
    | undefined,
  upsellProduct:
    | {
        sellPrice: number;
      }
    | null
    | undefined
) {
  if (!baseProduct || !upsellProduct) return null;
  return upsellProduct.sellPrice - baseProduct.sellPrice;
}

function getExtraDataText(
  baseProduct:
    | {
        data: string;
      }
    | null
    | undefined,
  upsellProduct:
    | {
        data: string;
      }
    | null
    | undefined
) {
  if (!baseProduct || !upsellProduct) return "—";

  const baseGb = parseDataGb(baseProduct.data);
  const upsellGb = parseDataGb(upsellProduct.data);

  if (baseGb === null || upsellGb === null) {
    return "Unlimited upgrade";
  }

  const extraGb = upsellGb - baseGb;

  if (extraGb <= 0) return "—";

  return `+${formatNumber(extraGb)}GB`;
}

function MiniProductCard({
  label,
  product,
}: {
  label: string;
  product:
    | {
        name: string;
        data: string;
        validityDays: number;
        sellPrice: number;
      }
    | null
    | undefined;
}) {
  return (
    <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4">
      <div className="text-xs font-black uppercase tracking-wide text-slate-500">
        {label}
      </div>

      <div className="mt-2 text-sm font-bold text-slate-950">
        {product ? product.name : "—"}
      </div>

      <div className="mt-1 text-sm text-slate-600">
        {product ? getPlanText(product) : "No product"}
      </div>

      <div className="mt-2 text-sm font-black text-blue-700">
        {product ? formatPrice(product.sellPrice) : "—"}
      </div>
    </div>
  );
}

export default async function UpsellsPage() {
  const [rules, settings] = await Promise.all([
    getRecommendationRulesPreview(),
    getRecommendationSettings(),
  ]);

  const finalUpsells = rules.filter((rule) => rule.upsellProduct).length;
  const comfortUpsells = rules.filter((rule) => rule.comfortOption).length;
  const heavyUpsells = rules.filter((rule) => rule.heavyDataOption).length;
  const regionalUpsells = rules.filter((rule) => rule.regionalUpsell).length;

  return (
    <AdminShell activePage="upsells">
      <div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div>
          <p className="text-sm font-bold uppercase tracking-wide text-blue-600">
            DALO Admin
          </p>

          <h1 className="mt-2 text-4xl font-bold text-slate-950">
            Upsells
          </h1>

          <p className="mt-2 max-w-3xl text-slate-600">
            This page previews customer-facing Smart Upgrade offers. Upsells are
            now generated by the same recommendation engine as the result page,
            not by simply choosing the next higher priced product.
          </p>
        </div>

        <a
          href="/admin/recommendations"
          className="rounded-2xl bg-blue-600 px-6 py-4 text-center font-bold text-white shadow-lg shadow-blue-200 transition hover:bg-blue-700"
        >
          Edit Rules
        </a>
      </div>

      <div className="mb-8 grid gap-6 md:grid-cols-4">
        <div className="rounded-[2rem] bg-white p-6 shadow-lg shadow-blue-50">
          <p className="text-sm font-semibold text-slate-500">
            Final Upsells
          </p>
          <h2 className="mt-3 text-3xl font-bold">{finalUpsells}</h2>
        </div>

        <div className="rounded-[2rem] bg-white p-6 shadow-lg shadow-blue-50">
          <p className="text-sm font-semibold text-slate-500">
            Comfort Offers
          </p>
          <h2 className="mt-3 text-3xl font-bold">{comfortUpsells}</h2>
        </div>

        <div className="rounded-[2rem] bg-white p-6 shadow-lg shadow-blue-50">
          <p className="text-sm font-semibold text-slate-500">
            Heavy Data Offers
          </p>
          <h2 className="mt-3 text-3xl font-bold">{heavyUpsells}</h2>
        </div>

        <div className="rounded-[2rem] bg-white p-6 shadow-lg shadow-blue-50">
          <p className="text-sm font-semibold text-slate-500">
            Regional Offers
          </p>
          <h2 className="mt-3 text-3xl font-bold">{regionalUpsells}</h2>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
        <div className="space-y-6">
          {rules.map((rule) => {
            const priceDifference = getPriceDifference(
              rule.recommendedProduct,
              rule.upsellProduct
            );

            return (
              <div
                key={`${rule.country}-${rule.tripLength}-${rule.userType}`}
                className="overflow-hidden rounded-[2rem] bg-white shadow-xl shadow-blue-50"
              >
                <div className="border-b border-slate-100 p-6">
                  <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
                    <div>
                      <div className="flex flex-wrap gap-2">
                        <span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-700">
                          {rule.country}
                        </span>

                        <span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold text-slate-700">
                          {rule.tripLength}
                        </span>

                        <span className="rounded-full bg-purple-100 px-3 py-1 text-sm font-bold text-purple-700">
                          {rule.userType}
                        </span>
                      </div>

                      <h2 className="mt-4 text-2xl font-bold text-slate-950">
                        {rule.upsellOffer?.title || "No customer upsell"}
                      </h2>

                      <p className="mt-1 text-slate-600">
                        {rule.upsellOffer?.subtitle ||
                          "No valid upgrade offer found for this scenario."}
                      </p>
                    </div>

                    <span
                      className={`rounded-full px-3 py-1 text-sm font-bold ${
                        rule.upsellProduct
                          ? "bg-green-100 text-green-700"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {rule.upsellProduct ? "Active" : "Missing Upsell"}
                    </span>
                  </div>
                </div>

                <div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3">
                  <MiniProductCard
                    label="Best Match"
                    product={rule.recommendedProduct}
                  />

                  <MiniProductCard
                    label="Final Customer Upsell"
                    product={rule.upsellProduct}
                  />

                  <div className="rounded-2xl border-2 border-blue-500 bg-blue-50 p-4">
                    <div className="text-xs font-black uppercase tracking-wide text-blue-700">
                      Customer Offer
                    </div>

                    <div className="mt-2 text-sm font-black text-slate-950">
                      {rule.upsellOffer?.title || "No offer"}
                    </div>

                    <div className="mt-3 grid grid-cols-2 gap-3">
                      <div className="rounded-xl bg-white p-3">
                        <div className="text-xs font-bold text-slate-500">
                          Extra Price
                        </div>
                        <div className="mt-1 font-black text-green-700">
                          {priceDifference !== null && priceDifference > 0
                            ? `+${formatPrice(priceDifference)}`
                            : "—"}
                        </div>
                      </div>

                      <div className="rounded-xl bg-white p-3">
                        <div className="text-xs font-bold text-slate-500">
                          Extra Data
                        </div>
                        <div className="mt-1 font-black text-blue-700">
                          {getExtraDataText(
                            rule.recommendedProduct,
                            rule.upsellProduct
                          )}
                        </div>
                      </div>
                    </div>

                    {rule.upsellOffer && (
                      <div className="mt-3 rounded-xl bg-white p-3 text-xs font-semibold text-slate-600">
                        Badge: {rule.upsellOffer.badge}
                      </div>
                    )}
                  </div>

                  <MiniProductCard
                    label="Comfort Candidate"
                    product={rule.comfortOption}
                  />

                  <MiniProductCard
                    label="Heavy Data Candidate"
                    product={rule.heavyDataOption}
                  />

                  <MiniProductCard
                    label="Regional Candidate"
                    product={rule.regionalUpsell}
                  />
                </div>
              </div>
            );
          })}
        </div>

        <div className="space-y-6">
          <div className="rounded-[2rem] bg-slate-950 p-8 text-white shadow-xl">
            <h2 className="text-2xl font-bold">Upsell Logic</h2>

            <p className="mt-2 text-slate-300">
              The customer sees one clear Smart Upgrade, not a list of cheaper
              alternatives.
            </p>

            <div className="mt-6 space-y-4">
              <div className="rounded-2xl bg-white/10 p-4">
                <div className="text-sm text-slate-400">Comfort</div>
                <div className="mt-1 font-bold">
                  More data than Best Match
                </div>
              </div>

              <div className="rounded-2xl bg-white/10 p-4">
                <div className="text-sm text-slate-400">Heavy Data</div>
                <div className="mt-1 font-bold">
                  Hotspot, video calls, streaming, work
                </div>
              </div>

              <div className="rounded-2xl bg-white/10 p-4">
                <div className="text-sm text-slate-400">Regional</div>
                <div className="mt-1 font-bold">
                  Europe plan for multi-country trips
                </div>
              </div>

              <div className="rounded-2xl bg-blue-600 p-4">
                <div className="text-sm text-blue-100">Customer Copy</div>
                <div className="mt-1 font-bold">
                  “Get 10GB more for only $4 extra”
                </div>
              </div>
            </div>
          </div>

          <div className="rounded-[2rem] bg-white p-8 shadow-xl shadow-blue-50">
            <h2 className="text-2xl font-bold text-slate-950">
              Current Upsell Settings
            </h2>

            <div className="mt-5 space-y-4 text-sm text-slate-700">
              {settings.map((setting) => (
                <div
                  key={setting.id}
                  className="rounded-2xl bg-slate-50 p-4"
                >
                  <div className="font-black text-slate-950">
                    {setting.label}
                  </div>

                  <div className="mt-2 leading-6">
                    Comfort multiple:{" "}
                    <strong>{setting.comfortMinNeedMultiple}×</strong>
                    <br />
                    Heavy min GB: <strong>{setting.heavyMinGb}GB</strong>
                    <br />
                    Budget internal min:{" "}
                    <strong>{setting.budgetMinNeedMultiple}×</strong>
                  </div>
                </div>
              ))}
            </div>

            <a
              href="/admin/recommendations"
              className="mt-6 block rounded-2xl bg-blue-50 px-5 py-4 text-center font-black text-blue-700 transition hover:bg-blue-100"
            >
              Edit settings →
            </a>
          </div>
        </div>
      </div>
    </AdminShell>
  );
}
